### ISSUE TITLE
AttributeError: 'ObjectNavDatasetV2' object has no attribute 'category_to_scene_annotation_category_id'

### ISSUE THREAD

**Issue by Yuxin916** [naokiyokoyama/ovon#20]
Hi! Thank you for your work! 

I noticed that the episode data OVON is slightly different from HM3D, especially in the episode.json file, original hm3d has keys like: episodes, category_to_task_category_id and category_to_scene_annotation_category_id. OVON only has episodes and goals_by_category. Therefore they need different data loader. 

When i load the ovon dataset using the registered ObjectNav-v2 (in your code), it output AttributeError: 'ObjectNavDatasetV1' object has no attribute 'category_to_scene_annotation_category_id'. I did not find how do you load the ovon dataset differently. 

Any suggestions on that? 

Thank you!

**Comment by Yonggie** [comment]
Hi, do you have any suggestion on how to uncompressed the navigation episode the author provide [in the link]( https://huggingface.co/datasets/nyokoyama/hm3d_ovon/)?

Because after I ``tar -zxvf`` this file, it still contains ``.gz`` file in uncompressed directory. But when I use gunzip to uncompressed the .gz, it'll prompt ``gzip: ./train/content/._gQgtJ9Stk5s.json.gz: not in gzip format``.

**Comment by Yuxin916** [comment]
Hi. I encountered the same problem. The ._gQgtJ9Stk5s.json.gz is the cache. There is gQgtJ9Stk5s.json.gz existing. You can delete the cache files and then try out.

**Comment by Yuxin916** [comment]
Hi. I encountered the same problem. The ._gQgtJ9Stk5s.json.gz is the cache. There is gQgtJ9Stk5s.json.gz existing. You can delete the cache files and then try out.

**Comment by Yonggie** [comment]
Man, what can I say, thank you!

**Comment by Heathcliff-saku** [comment]
@Yuxin916 Hi, I encountered the same problem. It occurred error 'ObjectNavDatasetV1' object has no attribute 'category_to_task_category_id'  when importing ovon episode using habitat's official configuration file: [https://github.com/facebookresearch/habitat-lab/blob/main/habitat-lab/habitat/config/benchmark/nav/objectnav/objectnav_hm3d.yaml] 
Do you have any suggestions?

**Comment by JelinR** [comment]
@Heathcliff-saku Hi, I had the same issue recently and I got it working by changing a few config fields. OVON uses a different dataset type (OVON-v1) and simulator (OVONSim-v0), so you would need to update these in your config. You might also need to override the lab_sensors with clip_objectgoal_sensor. 

And for loading all the relevant classes, I added the OVON config directory to Hydra's search path. These got it working for my case.

**Comment by Heathcliff-saku** [comment]
> [@Heathcliff-saku](https://github.com/Heathcliff-saku) Hi, I had the same issue recently and I got it working by changing a few config fields. OVON uses a different dataset type (OVON-v1) and simulator (OVONSim-v0), so you would need to update these in your config. You might also need to override the lab_sensors with clip_objectgoal_sensor.
> 
> And for loading all the relevant classes, I added the OVON config directory to Hydra's search path. These got it working for my case.

@JelinR Thank you my friend !! It did work as you suggested.
